#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export PATH="/home/fil/.nvm/versions/node/v16.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/fil/.local/share/JetBrains/Toolbox/scripts"
npx lint-staged
